### PR TITLE
catch aiohttp.ContentTypeError, etc.

### PR DESCRIPTION
**Pull request by Andeeeee**
…of "err" in response, format_help_for_context with cog version, error embed function so you don't have to write it every time

### CODE REVIEW

**Comment by OofChair** [comment]
Hi Andy,
I tested these cogs and I got this error: 
```python
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NameError: name 'ctx' is not defined```

If you could fix that that would be great. Thanks!

**Review by Just-Jojo — CHANGES_REQUESTED** [review]
Hey there, you seem to be missing a few things.

At line #57 you don't return the sending of the embed. If this error was caught it would most likely either error out or send the error embed twice.

At line #105 you do not include a `ctx` argument causing it to fail

Other than that it looks fine

**Comment by Andeeeee** [comment]
finished

**Comment by OofChair** [comment]
Thanks for doing that, I tested this and got this error:
```python
  File "/home/creepr/main/experimental/cogs/CogManager/cogs/redditpic/redditpic.py", line 87, in subr
    embed = await self.error_embed()
TypeError: error_embed() missing 1 required positional argument: 'ctx'
```
Please fix this, then I can merge this.

**Comment by kreusada** [comment]
There are still errors with this pull request as mentioned above, please test your code before submitting a PR because it wastes people's time trying to fix it for you

**Comment by OofChair** [comment]
I have tested this and it works successfully, thanks!

**Pull request merged**
